version: "3"
services: 
    api:
        build:
            context: ./express_backend
            dockerfile: Dockerfile.dev
        env_file: 
            - ./.env
        restart: always
        volumes: 
            - /app/node_modules
            - ./express_backend:/express_backend
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        depends_on: 
            - api
        restart: always
        volumes: 
            - ./nginx:/nginx
        ports: 
            - "8000:80"
            - "27017:27017"
